title: Evandro Macedo - Web Developer
name: Evandro Macedo
role: Web Developer
description: Evandro Macedo's personal website. Programming, Web Development, Cosmos, Meditation and life stuff.
email: evandro.hcm@gmail.com
baseurl: /
url: http://evandromacedo.com
paginate: 5
excerpt_separator: "<!-- more -->"
sass:
  style: :compressed
